services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    container_name: flask-app
    restart: unless-stopped
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      IBM_API_KEY: ${IBM_API_KEY}
    ports:
      - "5000:5000"
    depends_on:
      - db

  jupyter:
    image: jupyter/base-notebook
    container_name: jupyter-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./src:/home/jovyan/work
    environment:
      JUPYTER_TOKEN: 03fa11c6379462f3a1f767d7c915e1a7
    depends_on:
      - db

volumes:
  db-data:
